/*
 * This file is part of Rotorflight.
 *
 * Rotorflight is free software. You can redistribute this software
 * and/or modify this software under the terms of the GNU General
 * Public License as published by the Free Software Foundation,
 * either version 3 of the License, or (at your option) any later
 * version.
 *
 * Rotorflight is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public
 * License along with this software.
 *
 * If not, see <http://www.gnu.org/licenses/>.
 */

#pragma once

enum {
    PG_FAILSAFE_CONFIG                 =    1,
    PG_BOARD_ALIGNMENT                 =    2,
//  PG_GIMBAL_CONFIG                   =    3,
//  PG_MOTOR_MIXER                     =    4,
    PG_BLACKBOX_CONFIG                 =    5,
    PG_MOTOR_CONFIG                    =    6,
    PG_SENSOR_SELECTION_CONFIG         =    7,
    PG_SENSOR_ALIGNMENT_CONFIG         =    8,
    PG_SENSOR_TRIMS                    =    9,
    PG_GYRO_CONFIG                     =   10,
    PG_BATTERY_CONFIG                  =   11,
    PG_CONTROL_RATE_PROFILES           =   12,
    PG_SERIAL_CONFIG                   =   13,
    PG_PID_PROFILE                     =   14,
    PG_ARMING_CONFIG                   =   16,
    PG_SYSTEM_CONFIG                   =   18,
    PG_FEATURE_CONFIG                  =   19,
    PG_MIXER_CONFIG                    =   20,
    PG_SERVO_MIXER                     =   21,
    PG_IMU_CONFIG                      =   22,
    PG_PROFILE_SELECTION               =   23,
    PG_RX_CONFIG                       =   24,
    PG_RC_CONTROLS_CONFIG              =   25,
//  PG_MOTOR_3D_CONFIG                 =   26,
    PG_LED_STRIP_CONFIG                =   27,
    PG_COLOR_CONFIG                    =   28,
    PG_AIRPLANE_CONFIG                 =   29,
    PG_GPS_CONFIG                      =   30,
    PG_TELEMETRY_CONFIG                =   31,
    PG_FRSKY_TELEMETRY_CONFIG          =   32,
    PG_HOTT_TELEMETRY_CONFIG           =   33,
    PG_NAVIGATION_CONFIG               =   34,
    PG_ACCELEROMETER_CONFIG            =   35,
    PG_RATE_PROFILE_SELECTION          =   36,
//  PG_ADJUSTMENT_PROFILE              =   37,
    PG_ADJUSTMENT_RANGE_CONFIG         =   37,
    PG_BAROMETER_CONFIG                =   38,
    PG_COMPASS_CONFIG                  =   40,
    PG_MODE_ACTIVATION_PROFILE         =   41,
//  PG_SERVO_PROFILE                   =   42,
    PG_SERVO_PARAMS                    =   42,
//  PG_FAILSAFE_CHANNEL_CONFIG         =   43,
    PG_RX_FAILSAFE_CHANNEL_CONFIG      =   43,
//  PG_CHANNEL_RANGE_CONFIG            =   44,
    PG_RX_CHANNEL_RANGE_CONFIG         =   44,
    PG_MODE_COLOR_CONFIG               =   45,
    PG_SPECIAL_COLOR_CONFIG            =   46,
    PG_PILOT_CONFIG                    =   47,
    PG_MSP_SERVER_CONFIG               =   48,
    PG_VOLTAGE_METER_CONFIG            =   49,
    PG_AMPERAGE_METER_CONFIG           =   50,
    PG_DEBUG_CONFIG                    =   51,
    PG_SERVO_CONFIG                    =   52,
    PG_IBUS_TELEMETRY_CONFIG           =   53,
//  PG_VTX_CONFIG                      =   54,
    PG_POSITION                        =   56,
    PG_VTX_IO_CONFIG                   =   57,

    PG_DRIVER_PWM_RX_CONFIG            =  100,
    PG_DRIVER_FLASHCHIP_CONFIG         =  101,

    PG_CURRENT_SENSOR_ADC_CONFIG       =  256,
    PG_CURRENT_SENSOR_VIRTUAL_CONFIG   =  257,
    PG_VOLTAGE_SENSOR_ADC_CONFIG       =  258,
    PG_VTX_SETTINGS_CONFIG             =  259,

//  PG_MODE_ACTIVATION_OPERATOR_CONFIG =  500,
    PG_OSD_CONFIG                      =  501,
    PG_BEEPER_CONFIG                   =  502,
    PG_BEEPER_DEV_CONFIG               =  503,
    PG_PID_CONFIG                      =  504,
    PG_STATUS_LED_CONFIG               =  505,
    PG_FLASH_CONFIG                    =  506,
    PG_PPM_CONFIG                      =  507,
//  PG_PWM_CONFIG                      =  508,
    PG_SERIAL_PIN_CONFIG               =  509,
    PG_ADC_CONFIG                      =  510,
    PG_SDCARD_CONFIG                   =  511,
    PG_DISPLAY_PORT_MSP_CONFIG         =  512,
    PG_DISPLAY_PORT_MAX7456_CONFIG     =  513,
    PG_VCD_CONFIG                      =  514,
    PG_VTX_CONFIG                      =  515,
    PG_SONAR_CONFIG                    =  516,
    PG_ESC_SENSOR_CONFIG               =  517,
    PG_I2C_CONFIG                      =  518,
    PG_DASHBOARD_CONFIG                =  519,
    PG_SPI_PIN_CONFIG                  =  520,
    PG_ESCSERIAL_CONFIG                =  521,
    PG_CAMERA_CONTROL_CONFIG           =  522,
//  PG_RX_CC2500_SPI_CONFIG            =  523,
    PG_MAX7456_CONFIG                  =  524,
//  PG_FLYSKY_CONFIG                   =  525,
    PG_TIME_CONFIG                     =  526,
    PG_RANGEFINDER_CONFIG              =  527,
    PG_PINIO_CONFIG                    =  529,
    PG_PINIOBOX_CONFIG                 =  530,
    PG_USB_CONFIG                      =  531,
    PG_SDIO_CONFIG                     =  532,
    PG_DISPLAY_PORT_CRSF_CONFIG        =  533,
    PG_TIMER_IO_CONFIG                 =  534,
    PG_SPI_PREINIT_IPU_CONFIG          =  535,
    PG_SPI_PREINIT_OPU_CONFIG          =  536,
//  PG_RX_SPI_CONFIG                   =  537,
    PG_BOARD_CONFIG                    =  538,
    PG_RCDEVICE_CONFIG                 =  539,
    PG_GYRO_DEVICE_CONFIG              =  540,
    PG_MCO_CONFIG                      =  541,
//  PG_RX_SPEKTRUM_SPI_CONFIG          =  542,
    PG_SERIAL_UART_CONFIG              =  543,
    PG_LED_STRIP_STATUS_MODE_CONFIG    =  545,
    PG_VTX_TABLE_CONFIG                =  546,
    PG_STATS_CONFIG                    =  547,
    PG_QUADSPI_CONFIG                  =  548,
    PG_TIMER_UP_CONFIG                 =  549,
    PG_SDIO_PIN_CONFIG                 =  550,
    PG_PULLUP_CONFIG                   =  551,
    PG_PULLDOWN_CONFIG                 =  552,
    PG_MODE_ACTIVATION_CONFIG          =  553,
//  PG_RX_EXPRESSLRS_SPI_CONFIG        =  555,
    PG_SCHEDULER_CONFIG                =  556,
    PG_MSP_CONFIG                      =  557,
//  PG_SOFTSERIAL_PIN_CONFIG           =  558,
//  PG_GIMBAL_TRACK_CONFIG             =  559,
    PG_OPTICALFLOW_CONFIG              =  560,
    PG_BATTERY_PROFILES                =  561,
    PG_CAN_PIN_CONFIG                  =  563,
    PG_CAN_CONFIG                      =  564,
    PG_DRONECAN_CONFIG                 =  565,
    PG_DISPLAY_PORT_FBOSD_CONFIG       =  566,
    PG_DRONECAN_DNA_CONFIG             =  567,

    PG_OSD_FONT_CONFIG                 = 2047,
    PG_OSD_VIDEO_CONFIG                = 2046,
    PG_OSD_ELEMENT_CONFIG              = 2045,
    PG_OSD_CUSTOM_TEXT_CONFIG          = 2044,

    // Reserved for unit tests; never stored on a real FC.
    PG_RESERVED_FOR_TESTING_1          = 0xff01,
    PG_RESERVED_FOR_TESTING_2          = 0xff02,
    PG_RESERVED_FOR_TESTING_3          = 0xff03,
};
